### ISSUE TITLE
Update plugin to JOSM >= 10972

### ISSUE THREAD

**Issue by don-vip** [FreemapSlovakia/freemapKaPor#5]
The plugin needs to be updated with recent JOSM core changes, see https://josm.openstreetmap.de/ticket/13945

**Comment by don-vip** [comment]
Can you please update the plugin? We require Github plugin authors to either:
- maintain their plugin
- transfer it to the JOSM Github organization

Otherwise we have no other choice than banning the plugin.

**Comment by zdila** [comment]
Hello. I will check it in the following days / weeks.

**Comment by jose1711** [comment]
@don-vip could you please test with https://github.com/FreemapSlovakia/freemapKaPor/pull/6 ? i may have uploaded the wrong (old) version of plugin.

**Comment by don-vip** [comment]
@jose1711 It seems it does not work as we get more bug reports: https://josm.openstreetmap.de/ticket/14953

**Comment by jose1711** [comment]
well.. it did work but only until josm version 11826 (or so)
