### ISSUE TITLE
Plugin must be updated to JOSM 12881+

### ISSUE THREAD

**Issue by don-vip** [FreemapSlovakia/freemapKaPor#9]
See https://josm.openstreetmap.de/ticket/15310#comment:6

**Comment by don-vip** [comment]
Can you please update the plugin?

**Comment by zdila** [comment]
Unfortunately I have no time to fix it now. Feel free to remove it from JOSM.

**Comment by mkarpisek** [comment]
should be fixed with pull request #10

**Comment by zdila** [comment]
Reported from the users that it works. Thanks!
